################################################################################
# redis.conf
################################################################################

# Snapshot-based persistence (RDB)
save 60 10000
save 300 10
save 900 1

# Dump RDB File
dbfilename dump.rdb

# Diretorio onde o dump.rdb sera salvo
dir /data

# Rodar em primeiro plano (recomendado no Docker)
daemonize no

# Log no console
logfile ""

# Nivel de log
loglevel notice

# Protecao adicional (segura mesmo com senha)
protected-mode yes
